name: Deploy application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        since_last_remote_commit: true
        separator: ","

    - name: copy file to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        source: ${{ steps.changed-files.outputs.all_changed_files }}
        target: /home/site/zazai
